const SUPABASE_URL="https://tagbxmpizwlvgddgcpcl.supabase.co";const SUPABASE_KEY="sb_publishable_X36Iq53rm8U8HBkBfL06Vw_zErQRHK0";const supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);const $=id=>document.getElementById(id);let categories=[],products=[],allOrders=[];const esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));const money=v=>Number(v||0).toLocaleString("en-US",{style:"currency",currency:"USD"});const status=v=>String(v||"pending").toLowerCase();const withTimeout=(promise,label,ms=8000)=>Promise.race([promise,new Promise(resolve=>setTimeout(()=>resolve({data:null,error:{message:`${label} request timed out. Check Supabase/RLS.`}}),ms))]);
function showLogin(msg="",type="error"){$("dashboard")?.classList.add("hidden");$("loginSection")?.classList.remove("hidden");if($('loginMessage')){$('loginMessage').textContent=msg;$('loginMessage').className=msg?`message ${type}`:"message"}}
async function isAdmin(id){if(!id)return false;const {data,error}=await supabaseClient.from("admin_users").select("user_id").eq("user_id",id).maybeSingle();return !error&&!!data?.user_id}
async function checkLogin(){const {data,error}=await supabaseClient.auth.getSession();if(error||!data?.session){showLogin();return}if(!await isAdmin(data.session.user.id)){await supabaseClient.auth.signOut({scope:"local"});showLogin("Your account is authenticated, but it is not registered as an administrator.");return}await showDashboard(data.session)}
$("loginForm")?.addEventListener("submit",async e=>{e.preventDefault();showLogin();const email=$("email")?.value.trim(),password=$("password")?.value||"",b=$("loginForm")?.querySelector("button[type=submit]");if(b){b.disabled=true;b.textContent="Signing in..."}try{const {data,error}=await supabaseClient.auth.signInWithPassword({email,password});if(error)throw error;if(!await isAdmin(data.user.id)){await supabaseClient.auth.signOut({scope:"local"});throw new Error("Your account is not registered as an administrator.")}await showDashboard(data.session)}catch(e){showLogin(e.message||"Unable to sign in.")}finally{if(b){b.disabled=false;b.textContent="Sign in securely"}}});
async function showDashboard(session){$("loginSection")?.classList.add("hidden");$("dashboard")?.classList.remove("hidden");if($("adminEmailDisplay"))$("adminEmailDisplay").textContent=session.user.email||"";if($("adminEmail"))$("adminEmail").value=session.user.email||"";await refreshDashboard()}
async function loadCategories(){const c=$("categoriesContainer");if(!c)return;c.innerHTML='<div class="loading">Loading categories...</div>';const result=await withTimeout(supabaseClient.from("categories").select("*"),"Categories");if(result.error){c.innerHTML=`<div class="error-message">Unable to load categories: ${esc(result.error.message)}</div>`;return}categories=(result.data||[]).sort((a,b)=>String(a.name||a.title||"").localeCompare(String(b.name||b.title||"")));c.innerHTML=categories.length?categories.map(x=>`<div class="category-row"><strong>${esc(x.name||x.title||"Unnamed category")}</strong><small>${esc(x.slug||"")}</small></div>`).join(""):"<p>No categories found.</p>";populateCategorySelect()}
function populateCategorySelect(){const s=$("productCategory");if(!s)return;s.innerHTML='<option value="">Select category</option>'+categories.map(c=>`<option value="${esc(c.id)}">${esc(c.name||c.title||"")}</option>`).join("")}
async function loadProducts(){const table=$("itemsTable");if(!table)return;table.innerHTML='<tr><td colspan="5" class="loading">Loading products...</td></tr>';const result=await withTimeout(supabaseClient.from("products").select("*"),"Products");if(result.error){table.innerHTML=`<tr><td colspan="5" class="error-message">Unable to load products: ${esc(result.error.message)}</td></tr>`;return}products=result.data||[];products.sort((a,b)=>String(b.created_at||"").localeCompare(String(a.created_at||"")));renderProducts();updateInventorySummary()}
function renderProducts(){const table=$("itemsTable");if(!table)return;const rows=products.map(p=>{const s=Number(p.stock??p.quantity??p.inventory??0);return `<tr><td><strong>${esc(p.name||p.title||"Unnamed item")}</strong></td><td>${esc(p.category||p.category_name||"")}</td><td>${money(p.price??p.unit_price)}</td><td>${s}</td><td>${s<=0?'Out of stock':s<=5?'Low stock':'In stock'}</td></tr>`}).join("");table.innerHTML=rows||'<tr><td colspan="5">No products found.</td></tr>'}
function updateInventorySummary(){const n=products.length,low=products.filter(p=>{const s=Number(p.stock??p.quantity??p.inventory??0);return s>0&&s<=5}).length,out=products.filter(p=>Number(p.stock??p.quantity??p.inventory??0)<=0).length;if($("inventoryTotal"))$("inventoryTotal").textContent=n;if($("inventoryLow"))$("inventoryLow").textContent=low;if($("inventoryOut"))$("inventoryOut").textContent=out;if($("productCount"))$("productCount").textContent=n;if($("lowStock"))$("lowStock").textContent=low;if($("outStock"))$("outStock").textContent=out}
async function loadOrders(){const c=$("ordersContainer");if(!c)return;c.innerHTML='<div class="loading">Loading orders...</div>';const result=await withTimeout(supabaseClient.from("orders").select("*"),"Orders");if(result.error){c.innerHTML=`<div class="error-message">Unable to load orders: ${esc(result.error.message)}</div>`;return}allOrders=result.data||[];allOrders.sort((a,b)=>String(b.created_at||"").localeCompare(String(a.created_at||"")));renderOrders()}
function renderOrders(){const c=$("ordersContainer");if(!c)return;const q=($("orderSearch")?.value||"").toLowerCase(),f=$("orderStatusFilter")?.value||"";const rows=allOrders.filter(o=>{const text=JSON.stringify(o).toLowerCase();return(!q||text.includes(q))&&(!f||status(o.status)===f)}).map(o=>`<tr><td><strong>${esc(o.order_number||o.id||"—")}</strong></td><td>${esc(o.customer_name||o.name||o.email||o.customer_email||"Customer")}</td><td>${money(o.total??o.amount??o.total_amount)}</td><td>${o.created_at?new Date(o.created_at).toLocaleString():"—"}</td><td><span class="status-pill">${esc(status(o.status))}</span></td></tr>`).join("");c.innerHTML=`<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Date</th><th>Status</th></tr></thead><tbody>${rows||'<tr><td colspan="5">No orders found.</td></tr>'}</tbody></table></div>`}
async function loadStats(){try{const {data,error}=await withTimeout(supabaseClient.rpc("admin_dashboard_stats"),"Statistics",5000);if(error)throw error;if($("orderCount"))$("orderCount").textContent=data?.orders??allOrders.length;if($("revenue"))$("revenue").textContent=money(data?.revenue);if($("productCount"))$("productCount").textContent=data?.products??products.length}catch(e){if($("orderCount"))$("orderCount").textContent=allOrders.length;if($("revenue"))$("revenue").textContent="—"}}
async function refreshDashboard(){await Promise.allSettled([loadCategories(),loadProducts(),loadOrders()]);await loadStats()}
$("refresh")?.addEventListener("click",refreshDashboard);$("logoutButton")?.addEventListener("click",async()=>{await supabaseClient.auth.signOut({scope:"local"});showLogin()});$("orderSearch")?.addEventListener("input",renderOrders);$("orderStatusFilter")?.addEventListener("change",renderOrders);checkLogin();