// PanamaXChange storefront — products, categories, seller attribution, cart, checkout, and advanced filtering.
const SUPABASE_URL="https://tagbxmpizwlvgddgcpcl.supabase.co";
const SUPABASE_KEY="sb_publishable_X36Iq53rm8U8HBkBfL06Vw_zErQRHK0";
const supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:"panamaxchange-auth"}});
let products=[],categories=[],productSellers=new Map(),activeCategory="all";
function readCart(){try{const value=JSON.parse(localStorage.getItem("novashop-cart")||"[]");return Array.isArray(value)?value:[]}catch(error){console.warn("Invalid saved cart; resetting it.",error);return[]}}
let cart=readCart();
const $=id=>document.getElementById(id),productGrid=$("productGrid"),categoryFilters=$("categoryFilters"),searchInput=$("searchInput"),cartButton=$("cartButton"),cartCount=$("cartCount"),cartOverlay=$("cartOverlay"),closeCart=$("closeCart"),cartItems=$("cartItems"),cartTotal=$("cartTotal"),checkoutButton=$("checkoutButton"),checkoutOverlay=$("checkoutOverlay"),closeCheckout=$("closeCheckout"),checkoutForm=$("checkoutForm");
function money(value){const amount=Number(value);return `$${Number.isFinite(amount)?amount.toFixed(2):"0.00"}`}
function escapeHTML(value){return String(value??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;")}
function saveCart(){localStorage.setItem("novashop-cart",JSON.stringify(cart))}
function getProductCategory(product){if(typeof product.category==="string")return product.category;if(product.category&&typeof product.category==="object")return product.category.slug||product.category.name||"";return product.category_slug||product.category_name||""}
function getProductSeller(product){return product.owner_id?productSellers.get(String(product.owner_id))||"Registered seller":"PanamaXChange"}
function renderCategoryFilters(){categoryFilters.innerHTML="";const all=document.createElement("button");all.type="button";all.className=`category ${activeCategory==="all"?"active":""}`;all.dataset.category="all";all.textContent="All";categoryFilters.appendChild(all);categories.forEach(category=>{const slug=String(category.slug||category.name||"").toLowerCase(),button=document.createElement("button");button.type="button";button.className=`category ${activeCategory===slug?"active":""}`;button.dataset.category=slug;button.textContent=category.name||category.slug||"Category";categoryFilters.appendChild(button)})}
async function loadCategories(){try{const{data,error}=await supabaseClient.from("categories").select("id,name,slug").order("name",{ascending:true});if(error)throw error;categories=Array.isArray(data)?data:[]}catch(error){console.warn("CATEGORY ERROR:",error.message||error);categories=[]}renderCategoryFilters()}
async function loadProductSellers(){productSellers=new Map();const owned=products.filter(p=>p.owner_id).map(p=>Number(p.id));if(!owned.length)return;try{const{data,error}=await supabaseClient.rpc("get_product_sellers",{p_product_ids:owned});if(error)throw error;(data||[]).forEach(row=>{const product=products.find(item=>Number(item.id)===Number(row.product_id));if(product?.owner_id)productSellers.set(String(product.owner_id),row.seller_name||"Registered seller")})}catch(error){console.warn("SELLER ATTRIBUTION WARNING:",error.message||error)}}
async function loadProducts(){productGrid.innerHTML='<div class="loading">Loading products...</div>';try{const{data,error}=await supabaseClient.from("products").select("id,name,description,price,category,image_url,stock,owner_id").order("id",{ascending:true});if(error)throw error;products=Array.isArray(data)?data:[];await loadProductSellers();displayProducts();updateCart()}catch(error){console.error("PRODUCT ERROR:",error);products=[];productSellers=new Map();productGrid.innerHTML=`<div class="loading">Could not load products. ${escapeHTML(error?.message||"Please try again later.")} <button type="button" id="retryProducts" class="secondary-button">Retry</button></div>`;$("retryProducts")?.addEventListener("click",loadProducts);updateCart()}}
function getFilterState(){return{search:String(searchInput?.value||"").trim().toLowerCase(),min:Number($("productMinPrice")?.value||0),max:Number($("productMaxPrice")?.value||0),stock:$("productStockFilter")?.value||"all",sort:$("productSort")?.value||"featured"}}
function displayProducts(){const{search,min,max,stock,sort}=getFilterState();let filtered=products.filter(product=>{const category=String(getProductCategory(product)).trim().toLowerCase(),name=String(product.name||"").toLowerCase(),description=String(product.description||"").toLowerCase(),seller=String(getProductSeller(product)||"").toLowerCase(),price=Number(product.price||0),stockQty=Number(product.stock||0),stockMatch=stock==="all"||(stock==="in"&&stockQty>5)||(stock==="low"&&stockQty>0&&stockQty<=5)||(stock==="out"&&stockQty<=0);return(activeCategory==="all"||category===activeCategory)&&(!search||`${name} ${description} ${seller}`.includes(search))&&(!min||price>=min)&&(!max||price<=max)&&stockMatch});if(sort==="price-asc")filtered.sort((a,b)=>Number(a.price||0)-Number(b.price||0));else if(sort==="price-desc")filtered.sort((a,b)=>Number(b.price||0)-Number(a.price||0));else if(sort==="name-asc")filtered.sort((a,b)=>String(a.name||"").localeCompare(String(b.name||"")));else if(sort==="newest")filtered.sort((a,b)=>Number(b.id||0)-Number(a.id||0));productGrid.innerHTML="";$("productResultsCount")&&($("productResultsCount").textContent=`${filtered.length} ${filtered.length===1?"item":"items"}`);$("productFilterSummary")&&($("productFilterSummary").textContent=`${activeCategory==="all"?"All categories":activeCategory} · ${filtered.length} results`);if(!filtered.length){productGrid.innerHTML='<div class="loading">No products match your filters.</div>';return}filtered.forEach(product=>{const card=document.createElement("article");card.className="product-card";const image=product.image_url?`<img src="${escapeHTML(product.image_url)}" alt="${escapeHTML(product.name)}" class="product-photo" loading="lazy">`:'<div class="product-image" aria-hidden="true">🛍️</div>';card.innerHTML=`${image}<div class="product-info"><p class="product-category">${escapeHTML(getProductCategory(product))}</p><h3 class="product-name">${escapeHTML(product.name)}</h3><p>${escapeHTML(product.description||"")}</p><p class="product-seller">Posted by <strong>${escapeHTML(getProductSeller(product))}</strong></p><p class="product-price">${money(product.price)}</p><button type="button" class="add-button" data-id="${escapeHTML(product.id)}">Add to Cart</button></div>`;productGrid.appendChild(card)})}
function addToCart(productId){const product=products.find(item=>Number(item.id)===Number(productId));if(!product)return;const existing=cart.find(item=>Number(item.id)===Number(productId));if(existing)existing.quantity=Math.max(1,Number(existing.quantity)||0)+1;else cart.push({id:Number(productId),quantity:1});saveCart();updateCart()}
function removeFromCart(productId){cart=cart.filter(item=>Number(item.id)!==Number(productId));saveCart();updateCart()}
function changeQuantity(productId,amount){const item=cart.find(entry=>Number(entry.id)===Number(productId));if(!item)return;item.quantity=(Number(item.quantity)||0)+amount;if(item.quantity<=0)return removeFromCart(productId);saveCart();updateCart()}
function updateCart(){let total=0,count=0;cartItems.innerHTML="";const valid=[];cart.forEach(item=>{const product=products.find(entry=>Number(entry.id)===Number(item.id)),quantity=Number(item.quantity);if(!product||!Number.isFinite(quantity)||quantity<=0)return;valid.push({id:Number(item.id),quantity});total+=Number(product.price||0)*quantity;count+=quantity;const div=document.createElement("div");div.className="cart-item";const image=product.image_url?`<img src="${escapeHTML(product.image_url)}" alt="${escapeHTML(product.name)}">`:"🛍️";div.innerHTML=`<div class="cart-item-image">${image}</div><div class="cart-item-info"><h4>${escapeHTML(product.name)}</h4><p class="cart-item-price">${money(product.price)}</p><div class="quantity"><button type="button" data-action="minus" data-id="${escapeHTML(product.id)}">−</button><span>${quantity}</span><button type="button" data-action="plus" data-id="${escapeHTML(product.id)}">+</button><button type="button" class="remove" data-action="remove" data-id="${escapeHTML(product.id)}">Remove</button></div></div>`;cartItems.appendChild(div)});if(valid.length!==cart.length){cart=valid;saveCart()}if(!cart.length)cartItems.innerHTML='<div class="cart-empty">Your cart is empty.</div>';cartCount.textContent=String(count);cartTotal.textContent=money(total)}
function closeCartModal(){cartOverlay.classList.add("hidden");document.body.style.overflow=""}function closeCheckoutModal(){checkoutOverlay.classList.add("hidden");document.body.style.overflow=""}
productGrid.addEventListener("click",event=>{const button=event.target.closest(".add-button");if(!button)return;addToCart(Number(button.dataset.id));const original=button.textContent;button.textContent="Added ✓";button.disabled=true;setTimeout(()=>{button.textContent=original;button.disabled=false},800)});
categoryFilters.addEventListener("click",event=>{const button=event.target.closest(".category");if(!button)return;activeCategory=button.dataset.category||"all";categoryFilters.querySelectorAll(".category").forEach(item=>item.classList.toggle("active",item===button));displayProducts()});
["productMinPrice","productMaxPrice","productStockFilter","productSort"].forEach(id=>$(id)?.addEventListener("input",displayProducts));
searchInput.addEventListener("input",displayProducts);
$("clearProductFilters")?.addEventListener("click",()=>{searchInput.value="";$("productMinPrice").value="";$("productMaxPrice").value="";$("productStockFilter").value="all";$("productSort").value="featured";activeCategory="all";renderCategoryFilters();displayProducts()});
$("toggleProductFilters")?.addEventListener("click",()=>{const panel=document.querySelector(".filter-panel"),toggle=$("toggleProductFilters"),expanded=toggle.getAttribute("aria-expanded")==="true";panel?.classList.toggle("collapsed",expanded);toggle.setAttribute("aria-expanded",String(!expanded))});
cartItems.addEventListener("click",event=>{const button=event.target.closest("button");if(!button)return;const id=Number(button.dataset.id);if(button.dataset.action==="plus")changeQuantity(id,1);if(button.dataset.action==="minus")changeQuantity(id,-1);if(button.dataset.action==="remove")removeFromCart(id)});cartButton.addEventListener("click",()=>{updateCart();cartOverlay.classList.remove("hidden");document.body.style.overflow="hidden"});closeCart.addEventListener("click",closeCartModal);checkoutButton.addEventListener("click",()=>{if(!cart.length)return alert("Your cart is empty.");closeCartModal();checkoutOverlay.classList.remove("hidden");document.body.style.overflow="hidden"});closeCheckout.addEventListener("click",closeCheckoutModal);
checkoutForm.addEventListener("submit",async event=>{event.preventDefault();if(!cart.length)return alert("Your cart is empty.");const customerName=$("customerName").value.trim(),customerEmail=$("customerEmail").value.trim(),customerAddress=$("customerAddress").value.trim(),submitButton=checkoutForm.querySelector("button[type='submit']");submitButton.disabled=true;submitButton.textContent="Processing...";try{const{data:orderId,error}=await supabaseClient.rpc("create_order",{p_customer_name:customerName,p_customer_email:customerEmail,p_customer_address:customerAddress,p_items:cart});if(error)throw error;alert(`Order placed successfully! Order #${orderId}`);cart=[];saveCart();updateCart();checkoutForm.reset();closeCheckoutModal()}catch(error){alert(`Could not place order: ${error.message||"Unknown error"}`)}finally{submitButton.disabled=false;submitButton.textContent="Place Order"}});
cartOverlay.addEventListener("click",event=>{if(event.target===cartOverlay)closeCartModal()});checkoutOverlay.addEventListener("click",event=>{if(event.target===checkoutOverlay)closeCheckoutModal()});document.addEventListener("keydown",event=>{if(event.key==="Escape"){closeCartModal();closeCheckoutModal()}});
async function startStore(){updateCart();await Promise.all([loadCategories(),loadProducts()]);updateCart()}startStore().catch(error=>{console.error("STORE STARTUP ERROR:",error);productGrid.innerHTML=`<div class="loading">The store could not start. ${escapeHTML(error?.message||"Please refresh the page.")} <button type="button" id="retryStore" class="secondary-button">Retry</button></div>`;$("retryStore")?.addEventListener("click",()=>location.reload())});
