const URL='https://tagbxmpizwlvgddgcpcl.supabase.co';const KEY='sb_publishable_X36Iq53rm8U8HBkBfL06Vw_zErQRHKbF0';const sb=window.supabase.createClient(URL,KEY);const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
function showLogin(m=''){document.getElementById('dashboard')?.classList.add('hidden');document.getElementById('loginSection')?.classList.remove('hidden');if($('loginMessage'))$('loginMessage').textContent=m}
async function admin(){const s=await sb.auth.getSession();if(!s.data?.session)return false;const r=await sb.from('admin_users').select('user_id').eq('user_id',s.data.session.user.id).maybeSingle();if(r.error||!r.data)return false;document.getElementById('loginSection')?.classList.add('hidden');document.getElementById('dashboard')?.classList.remove('hidden');return true}
async function products(){const el=$('productId');if(!el)return;el.innerHTML='<option value="">Loading products...</option>';let r=await sb.from('products').select('id,name').order('name');if(r.error){el.innerHTML=`<option value="">Products unavailable</option>`;return}el.innerHTML=(r.data||[]).map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')||'<option value="">No products available</option>'}
async function auctions(){const el=$('auctionList');if(!el)return;el.innerHTML='<div>Loading auctions...</div>';try{let r=await sb.from('auctions').select('id,product_id,title,description,starts_at,ends_at,status,starting_bid,minimum_increment,current_bid,created_at').order('created_at',{ascending:false});if(r.error)throw r.error;const data=r.data||[];let names={};if(data.length){const ids=[...new Set(data.map(x=>x.product_id).filter(Boolean))];if(ids.length){const p=await sb.from('products').select('id,name').in('id',ids);(p.data||[]).forEach(x=>names[x.id]=x.name)}}el.innerHTML=data.length?data.map(a=>`<div class="auction-row"><div class="auction-row-top"><div><h4>${esc(a.title)}</h4><p>${esc(names[a.product_id]||'Product')}</p></div><span class="auction-status ${esc(a.status)}">${esc(a.status)}</span></div><p>Current bid: <strong>$${Number(a.current_bid||0).toFixed(2)}</strong></p><p>${new Date(a.starts_at).toLocaleString()} → ${new Date(a.ends_at).toLocaleString()}</p><div class="auction-actions"><button type="button" class="secondary-button edit-auction" data-id="${esc(a.id)}">Edit</button><button type="button" class="secondary-button end-auction" data-id="${esc(a.id)}">End now</button></div></div>`).join(''):'<div>No auctions yet.</div>';el.querySelectorAll('.edit-auction').forEach(b=>b.onclick=()=>edit(b.dataset.id));el.querySelectorAll('.end-auction').forEach(b=>b.onclick=()=>end(b.dataset.id))}catch(e){el.innerHTML=`<div class="error-message">Unable to load auctions: ${esc(e.message||e)}</div>`}}
async function edit(id){const r=await sb.from('auctions').select('*').eq('id',id).single();if(r.error)return alert(r.error.message);const a=r.data;$('auctionId').value=a.id;$('productId').value=a.product_id;$('title').value=a.title||'';$('description').value=a.description||'';$('startsAt').value=new Date(a.starts_at).toISOString().slice(0,16);$('endsAt').value=new Date(a.ends_at).toISOString().slice(0,16);$('startingBid').value=a.starting_bid??0;$('increment').value=a.minimum_increment??1;$('status').value=a.status||'scheduled';window.scrollTo({top:0,behavior:'smooth'})}
async function end(id){if(!confirm('End this auction now?'))return;const r=await sb.from('auctions').update({status:'ended',ends_at:new Date().toISOString()}).eq('id',id);if(r.error)return alert(`Unable to end auction: ${r.error.message}`);await auctions()}
$('loginForm')?.addEventListener('submit',async e=>{e.preventDefault();try{const r=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(r.error)throw r.error;if(!(await admin())){await sb.auth.signOut({scope:'local'});throw new Error('This account is not an administrator.')}await products();await auctions()}catch(e){showLogin(e.message||'Unable to sign in.')}});
$('logout')?.addEventListener('click',async()=>{await sb.auth.signOut({scope:'local'});location.replace('auctions-admin.html?loggedout=1')});
$('auctionForm')?.addEventListener('submit',async e=>{e.preventDefault();const b=e.target.querySelector('button[type="submit"]');b.disabled=true;b.textContent='Saving...';try{const s=new Date($('startsAt').value),n=new Date($('endsAt').value);if(!Number.isFinite(s.getTime())||!Number.isFinite(n.getTime())||n<=s)throw new Error('End time must be after start time.');const p={product_id:Number($('productId').value),title:$('title').value.trim(),description:$('description').value.trim()||null,starts_at:s.toISOString(),ends_at:n.toISOString(),starting_bid:Number($('startingBid').value),minimum_increment:Number($('increment').value),status:$('status').value};const id=$('auctionId').value;const r=id?await sb.from('auctions').update(p).eq('id',id):await sb.from('auctions').insert(p);if(r.error)throw r.error;e.target.reset();$('auctionId').value='';await products();await auctions()}catch(e){alert(`Unable to save auction: ${e.message||e}`)}finally{b.disabled=false;b.textContent='Save auction'}});
(async()=>{try{if(await admin()){await products();await auctions()}}catch(e){showLogin(e.message||'Unable to initialize auction management.')}})();