const URL='https://tagbxmpizwlvgddgcpcl.supabase.co';const KEY='sb_publishable_X36Iq53rm8U8HBkBfL06Vw_zErQRHK0';const sb=window.supabase.createClient(URL,KEY);const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
function showLogin(message=''){if($('dashboard'))$('dashboard').classList.add('hidden');if($('loginSection'))$('loginSection').classList.remove('hidden');if($('loginMessage'))$('loginMessage').textContent=message}
async function isAdmin(userId){if(!userId)return false;const {data,error}=await sb.from('admin_users').select('user_id').eq('user_id',userId).maybeSingle();return !error&&!!data?.user_id}
async function boot(){const {data,error}=await sb.auth.getSession();if(error||!data?.session){showLogin();return}if(!(await isAdmin(data.session.user.id))){await sb.auth.signOut({scope:'local'});showLogin('This account is not an administrator.');return}if($('loginSection'))$('loginSection').classList.add('hidden');if($('dashboard'))$('dashboard').classList.remove('hidden');await Promise.all([products(),auctions()])}
async function products(){const select=$('productId');if(!select)return;select.innerHTML='<option>Loading products...</option>';const {data,error}=await sb.from('products').select('id,name').order('name');if(error){select.innerHTML='<option value="">Unable to load products</option>';return}select.innerHTML=(data||[]).map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');if(!data?.length)select.innerHTML='<option value="">No products available</option>'}
async function auctions(){const list=$('auctionList');if(!list)return;list.textContent='Loading auctions...';const {data,error}=await sb.from('auctions').select('id,product_id,title,description,starts_at,ends_at,status,starting_bid,minimum_increment,current_bid,created_at,products(name)').order('created_at',{ascending:false});if(error){list.innerHTML=`<div class="error-message">Unable to load auctions: ${esc(error.message)}</div>`;return}list.innerHTML=data?.length?data.map(a=>`<div class="auction-row"><div class="auction-row-top"><div><h4>${esc(a.title)}</h4><p>${esc(a.products?.name||'')}</p></div><span class="auction-status ${esc(a.status)}">${esc(a.status)}</span></div><p>Current bid: <strong>$${Number(a.current_bid||0).toFixed(2)}</strong></p><p>${new Date(a.starts_at).toLocaleString()} → ${new Date(a.ends_at).toLocaleString()}</p><div class="auction-actions"><button type="button" class="secondary-button edit-auction" data-id="${esc(a.id)}">Edit</button><button type="button" class="secondary-button end-auction" data-id="${esc(a.id)}">End now</button></div></div>`).join(''):'<div>No auctions yet.</div>';list.querySelectorAll('.edit-auction').forEach(b=>b.onclick=()=>edit(b.dataset.id));list.querySelectorAll('.end-auction').forEach(b=>b.onclick=()=>end(b.dataset.id))}
async function edit(id){const {data,error}=await sb.from('auctions').select('*').eq('id',id).single();if(error){alert(error.message);return}$('auctionId').value=data.id;$('productId').value=data.product_id;$('title').value=data.title||'';$('description').value=data.description||'';$('startsAt').value=new Date(data.starts_at).toISOString().slice(0,16);$('endsAt').value=new Date(data.ends_at).toISOString().slice(0,16);$('startingBid').value=data.starting_bid??0;$('increment').value=data.minimum_increment??1;$('status').value=data.status||'scheduled';window.scrollTo({top:0,behavior:'smooth'})}
async function end(id){if(!confirm('End this auction now?'))return;const {error}=await sb.from('auctions').update({status:'ended',ends_at:new Date().toISOString()}).eq('id',id);if(error)alert(`Unable to end auction: ${error.message}`);else await auctions()}
$('loginForm')?.addEventListener('submit',async e=>{e.preventDefault();const button=e.target.querySelector('button[type="submit"]');if(button){button.disabled=true;button.textContent='Signing in...'}try{const {data,error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)throw error;if(!(await isAdmin(data.user.id))){await sb.auth.signOut({scope:'local'});throw new Error('This account is not an administrator.')}await boot()}catch(err){showLogin(err.message||'Unable to sign in.')}finally{if(button){button.disabled=false;button.textContent='Login'}}});
$('logout')?.addEventListener('click',async e=>{e.preventDefault();const button=e.currentTarget;button.disabled=true;button.textContent='Signing out...';await sb.auth.signOut({scope:'local'});try{localStorage.removeItem(`sb-${new URL(URL).hostname.split('.')[0]}-auth-token`)}catch{}location.replace('auctions-admin.html?loggedout=1')});
$('auctionForm')?.addEventListener('submit',async e=>{e.preventDefault();const button=e.target.querySelector('button[type="submit"]');if(button){button.disabled=true;button.textContent='Saving...'}try{const starts=new Date($('startsAt').value),ends=new Date($('endsAt').value);if(!Number.isFinite(starts.getTime())||!Number.isFinite(ends.getTime())||ends<=starts)throw new Error('End time must be after start time.');const payload={product_id:Number($('productId').value),title:$('title').value.trim(),description:$('description').value.trim()||null,starts_at:starts.toISOString(),ends_at:ends.toISOString(),starting_bid:Number($('startingBid').value),minimum_increment:Number($('increment').value),status:$('status').value};let result;if($('auctionId').value)result=await sb.from('auctions').update(payload).eq('id',Number($('auctionId').value));else result=await sb.from('auctions').insert(payload);if(result.error)throw result.error;e.target.reset();$('auctionId').value='';await products();await auctions()}catch(err){alert(`Unable to save auction: ${err.message||err}`)}finally{if(button){button.disabled=false;button.textContent='Save auction'}}});
sb.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT')showLogin()});boot();