/** PanamaXChange customer-facing live auction browser with search and advanced filters. */
(()=>{
  const auth=window.PanamaXChangeAuth,supabaseClient=auth?.client,grid=document.getElementById('auctionGrid'),modal=document.getElementById('bidModal'),closeBid=document.getElementById('closeBid'),submit=document.getElementById('submitBid'),amount=document.getElementById('bidAmount'),message=document.getElementById('bidMessage'),history=document.getElementById('bidHistory');
  let selected=null,auctions=[];
  const esc=value=>String(value??'').replace(/[&<>\"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
  const money=value=>Number(value||0).toLocaleString('en-US',{style:'currency',currency:'USD'});
  const countdown=end=>{const ms=new Date(end).getTime()-Date.now();if(!Number.isFinite(ms)||ms<=0)return'Ended';const seconds=Math.floor(ms/1000),days=Math.floor(seconds/86400),hours=Math.floor(seconds%86400/3600),minutes=Math.floor(seconds%3600/60),secs=seconds%60;return days?`${days}d ${hours}h ${minutes}m`:hours?`${hours}h ${minutes}m ${secs}s`:`${minutes}m ${secs}s`};
  function showError(error){console.error('[PanamaXChange auctions]',error);if(grid){grid.innerHTML=`<div class="loading">Unable to load live auctions: ${esc(error?.message||error||'Unknown error')}. <button type="button" class="secondary-button" id="retryAuctions">Retry</button></div>`;document.getElementById('retryAuctions')?.addEventListener('click',loadAuctions)}}
  async function loadAuctions(){if(!grid)return;if(!supabaseClient)return showError(new Error('Shared storefront authentication client is unavailable.'));grid.innerHTML='<div class="loading">Loading live auctions...</div>';try{const result=await supabaseClient.from('auctions').select('id,title,description,starts_at,ends_at,starting_bid,minimum_increment,current_bid,product_id,products(name,image_url)').eq('status','live').order('ends_at',{ascending:true});if(result.error)throw result.error;auctions=result.data||[];renderAuctions()}catch(error){showError(error)}}
  function filterAuctions(){const query=String(document.getElementById('auctionSearchInput')?.value||'').trim().toLowerCase(),min=Number(document.getElementById('auctionMinPrice')?.value||0),max=Number(document.getElementById('auctionMaxPrice')?.value||0),ending=document.getElementById('auctionEndingFilter')?.value||'all',sort=document.getElementById('auctionSort')?.value||'ending-soon',now=Date.now();let visible=auctions.filter(a=>{const bid=Number(a.current_bid||0),search=`${a.title||''} ${a.description||''} ${a.products?.name||''}`.toLowerCase(),hours=(new Date(a.ends_at).getTime()-now)/3600000;return(!query||search.includes(query))&&(!min||bid>=min)&&(!max||bid<=max)&&(ending==='all'||hours>=0&&hours<=Number(ending))});if(sort==='price-asc')visible.sort((a,b)=>Number(a.current_bid||0)-Number(b.current_bid||0));else if(sort==='price-desc')visible.sort((a,b)=>Number(b.current_bid||0)-Number(a.current_bid||0));else if(sort==='newest')visible.sort((a,b)=>Number(b.id||0)-Number(a.id||0));else visible.sort((a,b)=>new Date(a.ends_at)-new Date(b.ends_at));return visible}
  function renderAuctions(){const visible=filterAuctions();document.getElementById('auctionResultsCount').textContent=`${visible.length} ${visible.length===1?'auction':'auctions'}`;document.getElementById('auctionFilterSummary').textContent=`${visible.length} matching live auctions`;
    grid.innerHTML=visible.length?visible.map(auction=>{const image=auction.products?.image_url?`<img class="auction-image" src="${esc(auction.products.image_url)}" alt="${esc(auction.title||auction.products?.name||'Auction item')}" loading="lazy">`:'<div class="auction-image" aria-hidden="true"></div>';const min=Math.max(Number(auction.starting_bid)||0,(Number(auction.current_bid)||0)+(Number(auction.minimum_increment)||1));return `<article class="auction-card"><div>${image}</div><div class="auction-body"><p class="eyebrow">LIVE AUCTION</p><h3>${esc(auction.title||auction.products?.name||'Auction')}</h3><p class="auction-desc">${esc(auction.description||auction.products?.name||'')}</p><div class="auction-meta"><div><small>Current bid</small><strong>${money(auction.current_bid)}</strong></div><div><small>Ends in</small><strong class="countdown" data-end="${esc(auction.ends_at)}">${countdown(auction.ends_at)}</strong></div></div><button class="primary-button full-width bid-open" data-id="${esc(auction.id)}" data-min="${min}">Bid from ${money(min)} →</button></div></article>`}).join(''):'<div class="loading">No live auctions match your filters.</div>';
    grid.querySelectorAll('.bid-open').forEach(button=>button.addEventListener('click',async()=>{const{data,error}=await supabaseClient.auth.getSession();if(error){message.textContent=error.message;return}if(!data?.session){const user=await window.panamaxRequireAuth?.();if(!user)return}const auction=auctions.find(item=>String(item.id)===String(button.dataset.id));if(auction)openBid(auction,Number(button.dataset.min))}))}
  function openBid(auction,minimum){selected=auction;message.textContent='';amount.value=Number(minimum).toFixed(2);amount.min=Number(minimum).toFixed(2);document.getElementById('bidTitle').textContent=auction.title||auction.products?.name||'Auction';document.getElementById('bidMinimum').textContent=`Minimum next bid: ${money(minimum)}`;modal.classList.remove('hidden');loadHistory(auction.id)}
  async function loadHistory(auctionId){history.innerHTML='<span>Loading…</span>';const result=await supabaseClient.rpc('get_auction_bids',{p_auction_id:auctionId});if(result.error){history.innerHTML=`<span>${esc(result.error.message||'Bid history unavailable.')}</span>`;return}history.innerHTML=result.data?.length?result.data.map(bid=>`<div class="bid-history-row"><strong>${money(bid.amount)}</strong><span>${new Date(bid.created_at).toLocaleString()}</span></div>`).join(''):'<span>No bids yet.</span>'}
  async function placeBid(){if(!selected)return;submit.disabled=true;submit.textContent='Submitting…';message.textContent='';try{const{data,error:sessionError}=await supabaseClient.auth.getSession();if(sessionError)throw sessionError;if(!data?.session){const user=await window.panamaxRequireAuth?.();if(!user)return}const bid=Number(amount.value);if(!Number.isFinite(bid)||bid<=0)throw new Error('Enter a valid bid amount.');const result=await supabaseClient.rpc('place_bid',{p_auction_id:selected.id,p_amount:bid});if(result.error)throw result.error;message.textContent='Bid placed successfully!';await loadAuctions();await loadHistory(selected.id)}catch(error){console.error('[PanamaXChange bid]',error);message.textContent=error?.message||'Could not place bid.'}finally{submit.disabled=false;submit.textContent='Place bid →'}}
  function clearFilters(){document.getElementById('auctionSearchInput').value='';document.getElementById('auctionMinPrice').value='';document.getElementById('auctionMaxPrice').value='';document.getElementById('auctionEndingFilter').value='all';document.getElementById('auctionSort').value='ending-soon';renderAuctions()}
  function start(){if(!auth?.client){showError(new Error('Authentication client is not ready. Refresh the page and try again.'));return}submit?.addEventListener('click',placeBid);closeBid?.addEventListener('click',()=>modal.classList.add('hidden'));modal?.addEventListener('click',event=>{if(event.target===modal)modal.classList.add('hidden')});document.getElementById('refreshAuctions')?.addEventListener('click',loadAuctions);document.getElementById('auctionSearchInput')?.addEventListener('input',renderAuctions);['auctionMinPrice','auctionMaxPrice','auctionEndingFilter','auctionSort'].forEach(id=>document.getElementById(id)?.addEventListener('input',renderAuctions));document.getElementById('clearAuctionFilters')?.addEventListener('click',clearFilters);document.getElementById('toggleAuctionFilters')?.addEventListener('click',()=>{const panel=document.querySelector('.auction-filter-panel'),button=document.getElementById('toggleAuctionFilters'),expanded=button.getAttribute('aria-expanded')==='true';panel?.classList.toggle('collapsed',expanded);button.setAttribute('aria-expanded',String(!expanded))});setInterval(()=>document.querySelectorAll('[data-end]').forEach(element=>element.textContent=countdown(element.dataset.end)),1000);loadAuctions()}
  document.addEventListener('DOMContentLoaded',start);
})();