const SUPABASE_URL="https://tagbxmpizwlvgddgcpcl.supabase.co";
const SUPABASE_KEY="sb_publishable_X36Iq53rm8U8HBkBfL06Vw_zErQRHK0";
const supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const grid=document.getElementById('auctionGrid');const modal=document.getElementById('bidModal');const closeBid=document.getElementById('closeBid');const submit=document.getElementById('submitBid');const amount=document.getElementById('bidAmount');const message=document.getElementById('bidMessage');const history=document.getElementById('bidHistory');let selected=null;
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
const money=v=>Number(v||0).toLocaleString('en-US',{style:'currency',currency:'USD'});
function countdown(end){const ms=new Date(end)-Date.now();if(ms<=0)return 'Ended';const s=Math.floor(ms/1000),d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60),x=s%60;return d?`${d}d ${h}h ${m}m`:h?`${h}h ${m}m ${x}s`:`${m}m ${x}s`}
async function loadAuctions(){grid.innerHTML='<div class="loading">Loading live auctions...</div>';const {data,error}=await supabaseClient.from('auctions').select('id,title,description,starts_at,ends_at,starting_bid,minimum_increment,current_bid,product_id,products(name,image_url)').eq('status','live').order('ends_at');if(error){console.error(error);grid.innerHTML='<div class="loading">Unable to load auctions.</div>';return}if(!data?.length){grid.innerHTML='<div class="loading">No live auctions right now. Check back soon.</div>';return}grid.innerHTML=data.map(a=>{const image=a.products?.image_url?`<img class="auction-image" src="${esc(a.products.image_url)}" alt="${esc(a.title)}">`:'<div class="auction-image"></div>';const min=Math.max(Number(a.starting_bid)||0,(Number(a.current_bid)||0)+(Number(a.minimum_increment)||1));return `<article class="auction-card"><a href="#auction-${a.id}">${image}</a><div class="auction-body"><p class="eyebrow">LIVE AUCTION</p><h3>${esc(a.title)}</h3><p class="auction-desc">${esc(a.description||a.products?.name||'')}</p><div class="auction-meta"><div><small>Current bid</small><strong>${money(a.current_bid)}</strong></div><div><small>Ends in</small><strong class="countdown" data-end="${esc(a.ends_at)}">${countdown(a.ends_at)}</strong></div></div><button class="primary-button full-width bid-open" data-id="${a.id}" data-min="${min}">Bid from ${money(min)} →</button></div></article>`}).join('');grid.querySelectorAll('.bid-open').forEach(b=>b.addEventListener('click',()=>openBid(data.find(a=>String(a.id)===b.dataset.id),Number(b.dataset.min))));}
function openBid(a,min){selected=a;message.textContent='';amount.value=min.toFixed(2);amount.min=min;document.getElementById('bidTitle').textContent=a.title;document.getElementById('bidMinimum').textContent=`Minimum next bid: ${money(min)}`;modal.classList.remove('hidden');loadHistory(a.id)}
async function loadHistory(id){history.innerHTML='<span>Loading…</span>';const {data,error}=await supabaseClient.rpc('get_auction_bids',{p_auction_id:id});if(error){history.innerHTML='<span>Bid history unavailable.</span>';return}history.innerHTML=data?.length?data.map(b=>`<div class="bid-history-row"><strong>${money(b.amount)}</strong><span>${new Date(b.created_at).toLocaleString()}</span></div>`).join(''):'<span>No bids yet.</span>'}
submit.addEventListener('click',async()=>{if(!selected)return;submit.disabled=true;submit.textContent='Submitting…';message.textContent='';try{const {data:session}=await supabaseClient.auth.getSession();if(!session?.session){message.textContent='Please sign in to place a bid.';return}const bid=Number(amount.value);const {error}=await supabaseClient.rpc('place_bid',{p_auction_id:selected.id,p_amount:bid});if(error)throw error;message.textContent='Bid placed successfully!';await loadAuctions();await loadHistory(selected.id)}catch(e){console.error(e);message.textContent=e.message||'Could not place bid.'}finally{submit.disabled=false;submit.textContent='Place bid →'}});
closeBid.addEventListener('click',()=>modal.classList.add('hidden'));modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.add('hidden')});document.getElementById('refreshAuctions').addEventListener('click',loadAuctions);setInterval(()=>document.querySelectorAll('[data-end]').forEach(e=>e.textContent=countdown(e.dataset.end)),1000);loadAuctions();