let db=null;
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c])),money=v=>Number(v||0).toLocaleString('en-US',{style:'currency',currency:'USD'});let products=[],editing=null;const wait=async(p,ms=12000)=>Promise.race([p,new Promise((_,rej)=>setTimeout(()=>rej(new Error('Request timed out. Check Supabase connection and RLS permissions.')),ms))]);
/** Reuse the canonical Admin session and authorize administrators/moderators. */
async function auth(){db=window.PanamaAdminAuth?.client||db;if(!db){location.replace('admin.html?returnTo=products-admin.html');return false}const s=await wait(db.auth.getSession());if(s.error||!s.data?.session){location.replace('admin.html?returnTo=products-admin.html');return false}const userId=s.data.session.user.id;let role='';try{const r=await wait(db.rpc('current_user_role'));if(!r.error)role=String(r.data||'').toLowerCase()}catch(error){console.warn('current_user_role unavailable; checking admin membership',error)}if(role==='admin'||role==='moderator')return true;try{const r=await wait(db.from('admin_users').select('user_id').eq('user_id',userId).maybeSingle());if(!r.error&&r.data?.user_id)return true}catch(error){console.warn('admin_users fallback unavailable',error)}location.replace('admin.html?returnTo=products-admin.html');return false}
/** Load products from Supabase using the authenticated Admin client. */
async function load(){if(!(await auth()))return;const r=await wait(db.from('products').select('id,name,description,price,category,image_url,stock').order('name'));if(r.error){$('rows').innerHTML=`<tr><td colspan="6" class="error">Unable to load products: ${esc(r.error.message)}</td></tr>`;return}products=r.data||[];editing=null;render();summary()}
/** Update product summary cards. */function summary(){$('total').textContent=products.length;$('inStock').textContent=products.filter(p=>Number(p.stock||0)>5).length;$('low').textContent=products.filter(p=>Number(p.stock||0)>0&&Number(p.stock)<=5).length;$('out').textContent=products.filter(p=>Number(p.stock||0)<=0).length}
/** Render filtered product rows. */function render(){const q=($('search').value||'').toLowerCase(),f=$('stock').value;const list=products.filter(p=>(!q||`${p.name||''} ${p.category||''}`.toLowerCase().includes(q))&&(!f||(f==='in'&&Number(p.stock||0)>5)||(f==='low'&&Number(p.stock||0)>0&&Number(p.stock)<=5)||(f==='out'&&Number(p.stock||0)<=0)));$('rows').innerHTML=list.length?list.map(p=>editing===String(p.id)?editRow(p):row(p)).join(''):'<tr><td colspan="6" class="empty">No products found.</td></tr>';bind()}
/** Render a standard product row. */function row(p){const s=Number(p.stock||0);return `<tr><td><strong>${esc(p.name||'Unnamed')}</strong><span style="display:block;color:#718096;font-size:12px">#${esc(p.id)}</span></td><td>${esc(p.category||'—')}</td><td>${money(p.price)}</td><td><strong>${s}</strong></td><td><span class="pill">${s<=0?'Out of stock':s<=5?'Low stock':'In stock'}</span></td><td><div class="actions"><button class="btn" data-edit="${esc(p.id)}">Edit</button><button class="btn danger" data-remove="${esc(p.id)}">Remove</button></div></td></tr>`}
/** Render an inline edit row for a product. */function editRow(p){return `<tr class="row-edit"><td><input class="edit-input" data-f="name" value="${esc(p.name)}"><span style="display:block;color:#718096;font-size:12px">#${esc(p.id)}</span></td><td><input class="edit-input" data-f="category" value="${esc(p.category||'')}"></td><td><input class="edit-input" data-f="price" type="number" min="0" step="0.01" value="${esc(p.price)}"></td><td><input class="edit-input" data-f="stock" type="number" min="0" step="1" value="${esc(p.stock??0)}"></td><td>Editing</td><td><div class="actions"><button class="btn primary" data-save="${esc(p.id)}">Save</button><button class="btn" data-cancel>Cancel</button></div></td></tr>`}
/** Save an edited product through the staff RPC. */async function save(id){const tr=document.querySelector('.row-edit'),v=k=>tr.querySelector(`[data-f="${k}"]`).value.trim(),existing=products.find(p=>String(p.id)===String(id))||{};const payload={name:v('name'),category:v('category')||null,price:Number(v('price')),stock:Number(v('stock'))};if(!payload.name||!Number.isFinite(payload.price)||payload.price<0||!Number.isInteger(payload.stock)||payload.stock<0)return alert('Enter a valid name, price and whole-number stock.');const b=tr.querySelector('[data-save]');b.disabled=true;b.textContent='Saving...';const r=await wait(db.rpc('admin_update_product',{p_id:id,p_name:payload.name,p_description:existing.description||null,p_price:payload.price,p_category:payload.category,p_image_url:existing.image_url||null,p_stock:payload.stock}));if(r.error){b.disabled=false;b.textContent='Save';return alert(`Unable to save product: ${r.error.message}`)}await load()}
/** Remove a product through the protected staff RPC. */async function remove(id){if(!confirm('Remove this product from the storefront? This action cannot be undone.'))return;const r=await wait(db.rpc('admin_delete_product',{p_id:id}));if(r.error)return alert(`Unable to remove product: ${r.error.message}`);await load()}
/** Bind dynamic product table actions. */function bind(){document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{editing=String(b.dataset.edit);render()});document.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>{editing=null;render()});document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>save(b.dataset.save));document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>remove(b.dataset.remove))}$('search').oninput=render;$('stock').onchange=render;$('refresh').onclick=load;
const modal=$('productCreateModal'),closeModal=()=>{modal?.classList.add('hidden');document.body.style.overflow=''};$('new').onclick=()=>{modal?.classList.remove('hidden');document.body.style.overflow='hidden';$('name').focus()};$('cancelNew').onclick=closeModal;$('closeProductCreate').onclick=closeModal;modal?.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
/** Create a new product through the protected staff RPC. */$('saveNew').onclick=async()=>{if(!(await auth()))return;const p={name:$('name').value.trim(),category:$('category').value.trim()||null,price:Number($('price').value),stock:Number($('quantity').value),image_url:$('image').value.trim()||null,description:$('description').value.trim()||null};if(!p.name||!Number.isFinite(p.price)||p.price<0||!Number.isInteger(p.stock)||p.stock<0)return alert('Enter a valid name, price and stock.');const b=$('saveNew');b.disabled=true;b.textContent='Creating...';try{const r=await wait(db.rpc('admin_create_product',{p_name:p.name,p_description:p.description,p_price:p.price,p_category:p.category,p_image_url:p.image_url,p_stock:p.stock}));if(r.error)throw r.error;closeModal();['name','category','price','quantity','image','description'].forEach(id=>$(id).value='');await load()}catch(error){alert(`Unable to create product: ${error.message||'Unknown error'}`)}finally{b.disabled=false;b.textContent='Create product'}};
$('logout').onclick=()=>window.PanamaAdminAuth?.signOut?.();
document.addEventListener('DOMContentLoaded',()=>{db=window.PanamaAdminAuth?.client||null;load()});